/*
* Copyright 2023 by Timo von Oertzen and Andreas M. Brandmaier
* 
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*    http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
package importexport;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

import engine.ParameterReader;
import gui.graph.Edge;
import gui.graph.Graph;
import gui.graph.Node;
import gui.views.ModelView;

public class LavaanExport extends GenericSyntaxExport {


	
	public LavaanExport(ModelView modelView) {

		super(modelView);
		
		setPrefix("#\r\n# This model specification was automatically generated by Onyx\r\n#\r\n"+
		 "library(lavaan);\r\nmodelData <- read.table("+DATAFILENAME+", header = TRUE) ;"
		+"\r\n model<-\"\r\n");
		setPostfix("\"\r\nresult<-lavaan(model, data=modelData, fixed.x=FALSE, missing=\"FIML\")\r\nsummary(result, fit.measures=TRUE)");

	}
	
	public String getHeader() {return "Lavaan code";}
	
    public boolean isValid() {return !modelView.hasDefinitionEdges();}
    
	public String convert(String s)
	{
		/*if (s.length()>8) {
			s = s.substring(0, 8);
		}
		
		s=s.toUpperCase();
		*/
		s = super.replaceGreekLetters(s);
		
		//return s.replaceAll("/[^A-Za-z0-9\\(\\) ]/", "_");
		s = s.replaceAll("[^A-Za-z0-9]", "_");

		while( s.startsWith("_") ) {
			s = s.substring(1);
		}
		
		if (s.length()==0) { s="parameter";}
		
		return(s);
	}
	
	
	protected String createEdgeString(Edge edge, String keyword, ParameterReader startingValues, boolean useUniqueNames) {
		
		double value;
		if (useStartingValues && edge.isFree() && startingValues!=null) {
			value = startingValues.getParameterValue(edge.getParameterName());
		} else {
			value = edge.getValue();
		}

		String fix="";
		if (edge.isFixed()) {
			fix = value+"*";
			parameterSlotNames.add("fixed");
		} else {
			if (edge.getParameterName() == null) {
				fix = "";
			} else {
				parameterSlotNames.add(edge.getParameterName());
				
				fix = makeSaveString(edge.getParameterName())+"*";				
			}
		}
		
		String sname = makeSaveString(edge.getSource().getUniqueName(useUniqueNames), edge.getSource().getObservedVariableContainer());
		String tname = makeSaveString(edge.getTarget().getUniqueName(useUniqueNames), edge.getTarget().getObservedVariableContainer());
		
		if (edge.getSource().isMeanTriangle()) {
			sname = "1";
		}
		
		if (keyword.equals( "WITH")) {
				return (sname + " ~~ " + fix+tname)+"\n";
		} else if (keyword.equals( "BY")) {
				return (sname + "=~" + fix+tname)+"\n";
		} else if (keyword.equals( "ON")) {
			return (tname + " ~ " + fix+sname)+"\n";			
		} else if (keyword.equals("PseudoLatent")) {
			return (sname + "=~ 0 \n");
		} else if (keyword.equals("MEAN")) {
			return (tname + " ~ "+fix+"1\n");
		} else if (keyword.equals("ANONYMOUS_MEAN")) {
			return (tname + "~1");
		}
		
		return "";

	}

	public List<String> getParameterSlotNames() {return parameterSlotNames;}
}
